#Ubuntu based Hello World container
FROM ubuntu:18.04

LABEL version="1.0"
LABEL description="Ubuntu hello world image"
LABEL maintainer="Reysmer Valle <reysmerwvr@gmail.com>"

RUN apt-get update

CMD ["echo", "Hello World"]